name: Deploy Mini-Judge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Start Mini-Judge with DinD
      run: |
        # Set Docker host to use the DinD service
        export DOCKER_HOST=tcp://localhost:2375
        export DOCKER_TLS_VERIFY=0
        
        # Install Docker client
        sudo apt-get update
        sudo apt-get install -y docker.io
        
        # Verify Docker connection
        docker version
        docker info
        
        # Start the Mini-Judge server
        npm start &
        
        # Keep the service running
        sleep 300
    
    - name: Test Mini-Judge endpoints
      run: |
        # Wait for server to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:3000/problems || exit 1
        
        echo "Mini-Judge is running successfully!"
