name: Test Docker Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-execution:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Docker client
      run: |
        export DOCKER_HOST=tcp://localhost:2375
        export DOCKER_TLS_VERIFY=0
        sudo apt-get update
        sudo apt-get install -y docker.io
        docker version
    
    - name: Run Docker-based tests
      run: |
        export DOCKER_HOST=tcp://localhost:2375
        export DOCKER_TLS_VERIFY=0
        npm test
    
    - name: Test code execution
      run: |
        export DOCKER_HOST=tcp://localhost:2375
        export DOCKER_TLS_VERIFY=0
        
        # Test Python execution
        echo "print('Hello from Docker!')" > test.py
        docker run --rm -v $(pwd):/app python:3.12-slim python /app/test.py
        
        # Test C++ execution  
        echo '#include <iostream>
        int main() { std::cout << "Hello from Docker!" << std::endl; return 0; }' > test.cpp
        docker run --rm -v $(pwd):/app gcc:12 bash -c "cd /app && g++ test.cpp -o test && ./test"
        
        echo "✅ Docker code execution working perfectly!"
